[package]
name = "clipboard_share"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tracing             = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
arboard = { version = "3", features = ["wayland-data-control"] }
clipboard-master = "4"
image = "0.25.8"
